### ISSUE TITLE
getParentElement does not return parent element

### ISSUE THREAD

**Issue by Puru-rs** [sukgu/shadow-automation-selenium#1]
getParentElement does not return parent element

Steps:
1. First find the child element using findElement
2. Use the getParentElement by passing the element found in first step

Expected: Should return the parent element 

Actual: Throwing an exception:
org.openqa.selenium.JavascriptException: javascript error: object.childElements is not a function
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'RST-QAPURU', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 74.0.3729.6 (255758eccf3d24..., userDataDir: C:\Users\PARAMA~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:13202}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 75.0.3770.100, webStorageEnabled: true, webdriver.remote.sessionid: 7669a2eb87d2be4100635adcde4...}
Session ID: 7669a2eb87d2be4100635adcde4d021d

![image](https://user-images.githubusercontent.com/22681355/59850570-2bbaab80-9388-11e9-9551-960a93064208.png)

**Comment by sukgu** [comment]
This issue is fixed now with the release of version 0.0.7.
