### ISSUE TITLE
Add xpath locators to project or how to search by text

### ISSUE THREAD

**Issue by stserkovnikov** [sukgu/shadow-automation-selenium#18]
Hello Sushil,
Now we are able to use only css locators but they can't search by text. I tried something like "tag[innerText='text']", "tag[text='text']" and several other variants but they don't work. Do you have any workarounds to search components by text?

**Comment by 2erix** [comment]
@stserkovnikov I too would like the library to support XPATH but I will work on something and do a pull request if I can get something viable. 
In the meantime have a look at: https://subscription.packtpub.com/book/web_development/9781849515740/1/ch01lvl1sec16/locating-elements-using-text
CSS has the ability to locate items via string but you need to use the 'contains' solution like in the sample on the link.

**Comment by sukgu** [comment]
The contains() pseudo-class may not work with browsers that don't natively support CSS selectors. Also, it has been deprecated from CSS3 specification.

**Comment by sukgu** [comment]
#22 added xpath core executor https://github.com/sukgu/shadow-automation-selenium/commit/a7a7496d5e1e39d7d20083e0836a949a668bfbf7
