### ISSUE TITLE
CSS with double quotes having single quotes inside not working.

### ISSUE THREAD

**Issue by sukgu** [sukgu/shadow-automation-selenium#20]
**Describe the bug**
If we have a CSS like `shadow.find_element("div[label='QA']")` doesn't work and throws error. The same works fine when we have CSS like `shadow.find_element('div[label="QA"]')`

**To Reproduce**
1. Write code to find an element with an attribute value like `shadow.find_element("div[label='QA']")`
2. Run the code
3. See error

**Expected behavior**
It should work fine for single quotes and double quotes both.

**Comment by 2erix** [comment]
We are using your library at the moment to get us through a shadow hurdle and the following works fine for us: shadow.find_element("input[id='username']").
We use that structure for all of our usage in test and all are ok.

**Comment by 2erix** [comment]
Very appreciative of your good work on this repo by the way.

**Comment by sukgu** [comment]
Thanks @2erix . Yes,  it works sometimes and sometimes it breaks when the element is in-depth of more than 2 levels.

**Comment by sukgu** [comment]
Thanks, @2erix . Yes,  it works sometimes, and sometimes it breaks when the element is in-depth of more than 2 levels.

**Comment by sukgu** [comment]
This issue actually belongs to [pyshadow](https://github.com/sukgu/pyshadow) project. Closing this in here. Thanks @2erix
