### ISSUE TITLE
Implicit wait inside explicit 

### ISSUE THREAD

**Issue by jobecode** [sukgu/shadow-automation-selenium#21]
https://github.com/sukgu/shadow-automation-selenium/blob/ae744ac967798ae17160d84b44481b8eff74cd0c/src/main/java/io/github/sukgu/Shadow.java#L217

Hi there, you library is very useful, congratulations. However we noticed that test last too much when using it. We think it could be related to this implicit wait in the code. I have set the pollingTime up to 1 s. So in every findElement we have to wait, at least 1 second. This becomes unacceptable when we have 20 assertions we are adding 20 seconds to the execution. In our previous implementation assertions don't take more than 2 seconds. 

Have you planned to remove this wait?

**Comment by sukgu** [comment]
Thanks @carappsw , It will be a quick fix. We just need to move this sleep after checking `visible = isPresent(element);`

**Comment by carappsw** [comment]
Thank you very much

**Comment by sukgu** [comment]
After reading the code I found that this is not the issue behind your tests taking long in execution. We are already checking visibility before going in for loop.
https://github.com/sukgu/shadow-automation-selenium/blob/ae744ac967798ae17160d84b44481b8eff74cd0c/src/main/java/io/github/sukgu/Shadow.java#L215

The explicitWait uses a polling time to check for the visibility of the element.

I would like some more info on how you were executing it earlier and what has been changed now when using this library.
Thanks.

**Comment by carappsw** [comment]
Hi again, thanks for taking a look. Then, it should be something in how we call tests or even in the web application. I need to investigate because this started to happen since we use this library. But it might be a coincidence with another change. 
Thanks anyway. I'll contact you in case I realise something.

**Comment by sukgu** [comment]
Closing this issue as no info provided.
