### ISSUE TITLE
Getting FileNotFoundException

### ISSUE THREAD

**Issue by harshith-rs** [sukgu/shadow-automation-selenium#23]
When trying to get a shadow dom element, Im getting below exception in Shadow.class file in line 83
java.io.FileNotFoundException: resource\querySelector.js (The system cannot find the path specified)

I have added the below dependency as well
<dependencies>
        <dependency>
            <groupId>io.github.sukgu</groupId>
            <artifactId>automation</artifactId>
            <version>0.0.1</version>
        </dependency>
</dependencies>

Not sure whether Im missing anything here

**Comment by sukgu** [comment]
Version 0.0.1 was an unstable version. Please use the latest version 0.1.0
