### ISSUE TITLE
getAllObject fails if element is not present

### ISSUE THREAD

**Issue by kelunik** [sukgu/shadow-automation-selenium#25]
It fails with the following error:

```
org.openqa.selenium.JavascriptException:
javascript error: Cannot read property 'shadowRoot' of undefined
```

[Reading the code](https://github.com/sukgu/shadow-automation-selenium/blob/3fc07b0d2782021bf95d752306d832e78f92a986/resources/querySelector.js#L337-L340), it can't work correctly.

```js
parent = querySelectorDeep(multiLevelSelectors[0]);
if (parent === undefined) {
    parent = querySelectorDeep(multiLevelSelectors[0]).shadowRoot
}
```

Here it queries for `querySelectorDeep(multiLevelSelectors[0])`, if the result is undefined, it does the exact same thing again, but tries to access `.shadowRoot` afterwards, which obviously fails.

**Comment by sukgu** [comment]
It will be good to throw `NoSuchElementException` [reference](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/NoSuchElementException.html)
