### ISSUE TITLE
findElementsByXPath methods returning duplicate elements

### ISSUE THREAD

**Issue by aakashRepo** [sukgu/shadow-automation-selenium#26]
URL: https://www.bedbathandbeyond.com/store/s/dresser

Shadow shadow = new Shadow(driver);
List<WebElement> we = shadow.findElementsByXPath("//a[@role='listitem']");
for (WebElement w : we) {
    System.out.println(w.getText());
}

The count of WebElements returned should be the same as present in DOM and UI. But using methods findElementsByXPath it returns around 63 webelements(7 elements repeated 9 times).  This works fine using css selector findElements method. Facing issue only with findElementsByXPath.

![image](https://user-images.githubusercontent.com/22890310/112459715-258b0780-8d84-11eb-9253-053fe139b8b8.png)

FindElementsByXpath:
![image](https://user-images.githubusercontent.com/22890310/112459950-6551ef00-8d84-11eb-9855-074bc2b757f0.png)

css: findElements
![image](https://user-images.githubusercontent.com/22890310/112460399-dabdbf80-8d84-11eb-8c41-fef93dd071f9.png)

Browser: Chrome
Version: 89.0.4389.90
OS: Windows 10

**Comment by aakashRepo** [comment]
Still facing the same issue with xpath:
![image](https://user-images.githubusercontent.com/22890310/112966347-c7856800-9167-11eb-954e-bd91e2a7b06a.png)

**Comment by sukgu** [comment]
@aakashRepo which version you are using. The fix is released under v0.1.1

**Comment by aakashRepo** [comment]
Thanks, @sukgu I was using the old version. It is working fine.
