### ISSUE TITLE
shadow method for xpath throwing error when using pipe separator for 2 xpaths 

### ISSUE THREAD

**Issue by aakashRepo** [sukgu/shadow-automation-selenium#28]
**Xpath used:**  //div[@id='dskMenuLevel1']//button[@data-dsk-click='categories'] | //div[@id='dskMenuLevel1']//button[@data-dsk-click='Categories']

**Error Message:**
invalid element state: Failed to execute 'evaluate' on 'Document': The string './/button[@data-dsk-click='categories'] | ' is not a valid XPath expression.

Can't we use multiple xpaths in shadow library methods by adding pipe symbol as separator?

**Comment by sukgu** [comment]
This has not been implemented so far. This is a perfect candidate for enhancement. @aakashRepo

**Comment by aakashRepo** [comment]
HI, @sukgu any update on this enhancement?
