### ISSUE TITLE
findElementByXPath giving ElementNotVisibleException, however findElementsByXPath returning one element

### ISSUE THREAD

**Issue by aakashRepo** [sukgu/shadow-automation-selenium#29]
**Visit URL:** https://em02-www.bbbyapp.com/store/product/keurig-k-caf-eacute-special-edition-single-serve-coffee-latte-amp-cappuccino-maker/5211803?keyword=5211803&web3feo

**Steps to Reproduce:**
Click Heart icon on Product image
click "Create IdeaBoard" on popup
Enter some random text in Board Name
click Save

Now in below line we will get ElementNotVisibleException Exception if we don't add a browser refresh before it. We are trying to find 'Sign in' link present in Header
	    shadow.findElementByXPath("//div[contains(@class, 'dskAcctCont')]//a[@id = 'accountlink']");

**Error Message:**
org.openqa.selenium.ElementNotVisibleException: Element with XPath //div[contains(@class, 'dskAcctCont')]//a[@id = 'accountlink'] is not present on screen

![Screenshot (137)](https://user-images.githubusercontent.com/22890310/117295437-79affe00-ae91-11eb-9d44-11cdf4342668.png)
![Screenshot (136)](https://user-images.githubusercontent.com/22890310/117295445-7caaee80-ae91-11eb-8910-9192328242d0.png)

**Comment by sukgu** [comment]
@aakashRepo `ElementNotVisibleException` implies that the element is present but it's not visible on UI and that's why you are getting an item when using `findElementsByXPath`, maybe try to wait before it gets loaded properly on UI.

**Comment by aakashRepo** [comment]
@sukgu in this case the element is visible on UI but still facing this issue. The element is the 'sign in' link in header.

![image](https://user-images.githubusercontent.com/22890310/117561246-a5f69500-b0b2-11eb-857d-d0a58dde8b81.png)

**Comment by sukgu** [comment]
Please try this code.
`try {
			shadow.setExplicitWait(10, 1);
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		WebElement element = shadow.findElementByXPath("//div[contains(@class, 'headerRow2')]//p[@class='accountTxt']");
		element.click();
		try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}`

**Comment by sukgu** [comment]
@aakashRepo Please try this code.
```
               try {
                    shadow.setExplicitWait(10, 1);
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		WebElement element = shadow.findElementByXPath("//div[contains(@class, 'headerRow2')]//p[@class='accountTxt']");
		element.click();
		try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```

**Comment by aakashRepo** [comment]
Hi, @sukgu we still face this issue at multiple places.
If we call shadow.findElementsByXPath, it returns us the element or elements
on calling shadow.isVisible on the element/elements it gives false for all of them even though the element is visible on UI.
This is the same issue that happened on calling shadow.findElementByXPath as shared earlier.

**Comment by aakashRepo** [comment]
I have observed one more issue that using // multiple times in a xpath is causing issues. 
It returns elementnotvisible exception
