### ISSUE TITLE
Indexing in xpath is not working

### ISSUE THREAD

**Issue by aakashRepo** [sukgu/shadow-automation-selenium#30]
The xpath doesn't allow indexing like below:
(//h1[@class='Heading'])[1]
**Getting Exception**
invalid element state: Failed to execute 'evaluate' on 'Document': The string '(//h1[@class='Heading'])[1]' is not a valid XPath expression.

**Comment by sukgu** [comment]
Indexing is not supported for now as we have a workaround for that. You can always use indexing in returned elements list.

**Comment by sukgu** [comment]
@aakashRepo Indexing is not supported for now as we have a workaround for that. You can always use indexing in returned elements list.

**Comment by aakashRepo** [comment]
Thanks @sukgu 
Yes, we are using the workaround as of now. However, indexing is really helpful while automation of UI as we don't have to collect all the elements everytime in the list. It would be really good if this is also prioritized later on whenever we can.
