### ISSUE TITLE
Nullpointerexception when calling the Shadow constructor

### ISSUE THREAD

**Issue by KrischnaGabriel** [sukgu/shadow-automation-selenium#37]
When trying to create an instance of shadow with the Shadow(WebDriver driver) constructor, i get this error:

> Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at io.github.sukgu.Shadow.convertJStoText(Shadow.java:124)
	at io.github.sukgu.Shadow.<init>(Shadow.java:42)
	at sed.main(sed.java:109)

**To Reproduce**
1. Open a WebBrowser with debug port open (test was done with chromium based browser)
2. connect selenium to the browser. ( i am using selenium 4.0.0 something as i forked selenium and didn't wanted to migrate my code when it still works)
3. Validate the driver works by opening a site or something.
4. (try to) create a Shadow instance with the driver object.

**Desktop (please complete the following information):**
 - OS: linux mint version: the most recent one
 - Chrome, Chromium.. doesn't really matter; tested valid on Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)
 - Selenium 4.0.0 beta 2 fork (fork only adds some methods, doesn't breaks any functionality)

**test Code snippets**
in bash:
`google-chrome --remote-debugging-port=9001`
in java

`
	import io.github.sukgu.Shadow
	;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.WebElement;
	
	import org.openqa.selenium.chrome.ChromeDriver;
	
	import org.openqa.selenium.interactions.Actions;
	
	import org.openqa.selenium.chrome.ChromeOptions;
	
	import org.openqa.selenium.JavascriptExecutor;
	
	public class test {
		public static WebDriver driver;
		public static JavascriptExecutor js;
		public static Actions actions;
	
		public static void main(String[] args) {
			ChromeOptions options = new ChromeOptions();
	
			System.setProperty("webdriver.chrome.driver", "webdivers/chromedriver"); 
	
			//--remote-debugging-port=9000
			options.setExperimentalOption("debuggerAddress","localhost:9001");
	
	
			driver = new ChromeDriver(options);
			js = (JavascriptExecutor) driver;
			actions = new Actions(driver);
			
	 		// validates if the Webdriver actually controls the browser
			driver.get("chrome://settings/");
	
			Shadow shadow = new Shadow(driver);
		}
	}`

console output:

> Starting ChromeDriver 92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}) on port 12936
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Aug 24, 2021 11:30:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Aug 24, 2021 11:30:22 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 92, so returning the closest version found: 91
Aug 24, 2021 11:30:22 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 92 of 91
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at io.github.sukgu.Shadow.convertJStoText(Shadow.java:124)
	at io.github.sukgu.Shadow.<init>(Shadow.java:42)
	at test.main(test.java:36)

**Comment by KrischnaGabriel** [comment]
nvm, the second answer of this stackoverflow thread solved the shadow-root problem as well.
https://stackoverflow.com/questions/55761810/how-to-automate-shadow-dom-elements-using-selenium
So it's not such a big deal

**Comment by sukgu** [comment]
This tool is developed and tested on Selenium version 3.x.x. Selenium 4 beta support is in development.
