### ISSUE TITLE
Query - WaitForVisibilityofShadowElement(String xPath)

### ISSUE THREAD

**Issue by ajmera25** [sukgu/shadow-automation-selenium#38]
Sorry for raising query as a bug. Wanted to know if there is way for waitForVisibilityOfShadowElement(String xPath)?

**Comment by sukgu** [comment]
You can use 2 overloaded findElementByXPath() methods. It internally waits for visibility for the time you set as explicitWait with polling intervals. For setting explicit wait please check setExplicitWait() method in [documentation](https://github.com/sukgu/shadow-automation-selenium/wiki/Documentation).

**Comment by ajmera25** [comment]
Thanks.
