### ISSUE TITLE
Find element returns null when there multiple level of >

### ISSUE THREAD

**Issue by Puru-rs** [sukgu/shadow-automation-selenium#4]
Find element returns null when there multiple level:

Below line of code return null though element exists:
WebElement textboxCollection3 = shadow.findElement(textboxCollection2,"pebble-textbox>paper-input>paper-input-container>iron-input>input");

**Comment by sukgu** [comment]
@Puru-rs  Can you please attach a snapshot of DOM structure?

**Comment by sukgu** [comment]
This is an enhancement that will enable 5 levels of DOM traversal.
Example: 
`WebElement textboxCollection3 = shadow.findElement(textboxCollection2,"pebble-textbox>paper-input>paper-input-container>iron-input>input")`
