### ISSUE TITLE
Maven/Gradle latest version 0.1.3 does not include the implicit/Explicit wait methods

### ISSUE THREAD

**Issue by mateiQA** [sukgu/shadow-automation-selenium#40]
When setting up the project either using pom maven - or build gradle files, the latest version there (0.1.3) does not include the implicit and explicit wait methods

Can you push the latest master artifact there as well, please?

Sceenshot of the Shadow Class downloaded from maven/gradle. The first few lines should contain:
	private int implicitWait = 0;
	private int explicitWait = 0;
	private int pollingTime = 0;
<img width="723" alt="Screenshot 2022-01-20 at 17 02 53" src="https://user-images.githubusercontent.com/42138146/150364318-ef49f418-95b0-433f-a9b5-45f43b7980b2.png">
Kind regards,
Matei

**Comment by sukgu** [comment]
@mateiQA  I checked in the maven central repository https://repo1.maven.org/maven2/io/github/sukgu/automation/0.1.3/ and the sources contain the missing lines. If I am looking at the wrong location, please provide more information.

**Comment by mateiQA** [comment]
Hello @sukgu.

Totally my mistake, I had a difference between the pom version and the gradle version of your library. I ended up using an older version which did not have those methods.
Sorry for the trouble, this can be closed

Have a wonderful day and thanks for the contribution,
Matei

**Comment by sukgu** [comment]
Thanks @mateiQA
