### ISSUE TITLE
Getting NoSuchElementException when trying to run on linux remote instance via jenkins

### ISSUE THREAD

**Issue by Dashanan1** [sukgu/shadow-automation-selenium#58]
**Describe the bug**
When i try to run the same code using Local machine(Mac+GoogleChrome(103.0.5060.114) do not gets any error but when trying to run using pipeline jenkins project with linux instance and chrome version - 100.0.4896.75 (os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.68-62.173.amzn2.x86_64', java.version: '1.8.0_121') getting "NoElementFound" despite waiting long as explicit wait.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sukgu** [comment]
It should not be a problem as our plugin test cases run on Linux machines always.
I would recommend it to run in headless mode or with Xvfb setup. 

Are you getting errors with shadow objects only? @Dashanan1 
Did you try manually on linux machine?

**Comment by sukgu** [comment]
Closing this as invalid.
