### ISSUE TITLE
Does this library supports selenium 4.6.0?

### ISSUE THREAD

**Issue by sabyamohapatra** [sukgu/shadow-automation-selenium#62]
**Describe the bug**
I am getting this error while using with Selenium 4.6.0
java.lang.NoSuchMethodError : org.openqa.sleenium.WebDriverTimeouts.implicitlywait

@sukgu

**Comment by sabyamohapatra** [comment]
Hi Team,
Can you please reply on above queries?

**Comment by anoopsimon** [comment]
@sabyamohapatra  Current version is using Seleniu, 4.14 version.
We are working on upgraded selenium.

**Comment by Ansuman0** [comment]
This issue has been Resolved and Push a branch with fixes  you can Review and verify it.

**Comment by lmrio** [comment]
Are you going to merge that PR? Thanks!

**Comment by Ansuman0** [comment]
> Are you going to merge that PR? Thanks!

If  you  Feel My changes  working fine and verifyd   you can merge it to your   main branch .

**Comment by ManishankarT** [comment]
> @sabyamohapatra Current version is using Selenium, 3.14 version. We are working on upgraded selenium.

Any update on the new version with upgraded selenium.  We are unable to use devtools with the existing version due to selenium 3.14

**Comment by sukgu** [comment]
The latest release Shadow 0.1.5 supports (tested and verified on) Selenium version 4.16.1 @anoopsimon @lmrio @ManishankarT @sabyamohapatra @Ansuman0
