### ISSUE TITLE
shadow-root type

### ISSUE THREAD

**Issue by ariksa** [sukgu/shadow-automation-selenium#7]
Hi,

I was trying to use shadow-automation-selenium to get elements inside closed shadow-root, but without any luck.
I was wondering if this is supported in your framework?

**Comment by sukgu** [comment]
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

We can't access closed shadow dom from document javascript. Closed shadow DOM is developed to serve this purpose.
