### ISSUE TITLE
Unable to locate shadow-root(closed) element getting no-such-element-exception 

### ISSUE THREAD

**Issue by rakesh-das2** [sukgu/shadow-automation-selenium#74]
**Describe the bug**
Unable to locate shadow-root(closed) element getting no-such-element-exception 

**To Reproduce**
1. Execute below snippet code
` public static void main(String[] args) throws Exception {
        WebDriver driver = new ChromeDriver();
        // Navigate to a website
        driver.get("https://www.boschaftermarket.com/xc/en/keysecure.html");

        Shadow shadow = new Shadow(driver);
        //Code to locale shadow root open element
        WebElement element = shadow.findElement("button[class='a-button a-button--primary -without-icon']");
        element.click();
        shadow.setExplicitWait(10, 1);

        //Code to locale shadow root closed element
        element = shadow.findElement("input[type='text']");
        element.sendKeys("Shadow closed element");
        shadow.setExplicitWait(10, 1);
`

**Expected behavior**
        **element = shadow.findElement("input[type='text']");** should able to locate the element inside shadow -root closed 

**Application Screenshots**
![image](https://github.com/user-attachments/assets/5e37d82a-d448-465f-9e54-7bd9a25711ed)

**Actual behavior**
Getting no-such-element exception

**Error Screenshots**
If applicable, add screenshots to help explain your problem.,
![image](https://github.com/user-attachments/assets/a67c056c-3a76-4813-adec-eda52d830bf7)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] 128

**Comment by sukgu** [comment]
If shadow root is closed then we can't find it using this tool. This is a limitation. This tool will only work if shadow root is open
